"""add last_reminded_at to users

Revision ID: c1a9743e2452
Revises: 1edde69cee05
Create Date: 2025-11-27 07:53:30.114647

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "c1a9743e2452"
down_revision: Union[str, Sequence[str], None] = "1edde69cee05"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("last_reminded_at", sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "last_reminded_at")
    # ### end Alembic commands ###
