// Auto-generated by scripts/generate-version.ts
// Do not edit manually.

export const VERSION = "3633df7e";
export const COMMIT = "3633df7e287417b66cf0c9073e6f74df84e69248";
export const BUILT_AT = "2026-05-15T05:28:47.082Z";
export const ENVIRONMENT = "development";
export const SERVICE_NAME = "cf-bot";

export interface VersionInfo {
  version: string;
  commit: string;
  builtAt: string;
  environment: string;
  service: string;
}

export function getVersionInfo(): VersionInfo {
  return {
    version: VERSION,
    commit: COMMIT,
    builtAt: BUILT_AT,
    environment: ENVIRONMENT,
    service: SERVICE_NAME,
  };
}

export function formatDuration(isoDate: string): string {
  const then = new Date(isoDate).getTime();
  const now = Date.now();
  const diff = Math.max(0, now - then);
  const seconds = Math.floor(diff / 1000);
  const minutes = Math.floor(seconds / 60);
  const hours = Math.floor(minutes / 60);
  const days = Math.floor(hours / 24);
  if (days > 0) return `${days}d ${hours % 24}h ago`;
  if (hours > 0) return `${hours}h ${minutes % 60}m ago`;
  if (minutes > 0) return `${minutes}m ago`;
  return `${seconds}s ago`;
}
