#!/usr/bin/env node
/**
 * Generate version.ts for each CF service.
 *
 * Uses git tag for production releases, short commit hash for dev.
 * Also captures build timestamp.
 */

import { execSync } from "child_process";
import { writeFileSync, mkdirSync } from "fs";
import { dirname } from "path";

interface VersionInfo {
  version: string;
  commit: string;
  builtAt: string;
  environment: "development" | "production";
}

function getGitInfo(): VersionInfo {
  // Try to get the current git tag (for prod releases)
  let version: string;
  try {
    version = execSync("git describe --tags --exact-match HEAD", {
      encoding: "utf-8",
      stdio: ["pipe", "pipe", "ignore"],
    }).trim();
  } catch {
    // No exact tag — use short commit hash
    version = execSync("git rev-parse --short HEAD", {
      encoding: "utf-8",
    }).trim();
  }

  const commit = execSync("git rev-parse --short HEAD", {
    encoding: "utf-8",
  }).trim();

  const builtAt = new Date().toISOString();

  // Determine environment from CI or git tag presence
  const isProd =
    process.env.CF_ENV === "production" ||
    process.env.GITHUB_REF?.startsWith("refs/tags/v");

  return {
    version,
    commit,
    builtAt,
    environment: isProd ? "production" : "development",
  };
}

function generateVersionFile(
  servicePath: string,
  info: VersionInfo,
  serviceName: string
) {
  const filePath = `${servicePath}/src/lib/version.ts`;
  mkdirSync(dirname(filePath), { recursive: true });

  const content = `// Auto-generated by scripts/generate-version.ts
// Do not edit manually.

export const VERSION = ${JSON.stringify(info.version)};
export const COMMIT = ${JSON.stringify(info.commit)};
export const BUILT_AT = ${JSON.stringify(info.builtAt)};
export const ENVIRONMENT = ${JSON.stringify(info.environment)};
export const SERVICE_NAME = ${JSON.stringify(serviceName)};

export interface VersionInfo {
  version: string;
  commit: string;
  builtAt: string;
  environment: string;
  service: string;
}

export function getVersionInfo(): VersionInfo {
  return {
    version: VERSION,
    commit: COMMIT,
    builtAt: BUILT_AT,
    environment: ENVIRONMENT,
    service: SERVICE_NAME,
  };
}

export function formatDuration(isoDate: string): string {
  const then = new Date(isoDate).getTime();
  const now = Date.now();
  const diff = Math.max(0, now - then);

  const seconds = Math.floor(diff / 1000);
  const minutes = Math.floor(seconds / 60);
  const hours = Math.floor(minutes / 60);
  const days = Math.floor(hours / 24);

  if (days > 0) return \`\${days}d \${hours % 24}h ago\`;
  if (hours > 0) return \`\${hours}h \${minutes % 60}m ago\`;
  if (minutes > 0) return \`\${minutes}m ago\`;
  return \`\${seconds}s ago\`;
}
`;

  writeFileSync(filePath, content, "utf-8");
  console.log(`Generated ${filePath}`);
  console.log(`  version: ${info.version}`);
  console.log(`  commit: ${info.commit}`);
  console.log(`  builtAt: ${info.builtAt}`);
  console.log(`  environment: ${info.environment}`);
}

const info = getGitInfo();

generateVersionFile("services/cf-api", info, "cf-api");
generateVersionFile("services/cf-bot", info, "cf-bot");
generateVersionFile("services/cf-worker", info, "cf-worker");

console.log("\nVersion files generated successfully.");
