#!/usr/bin/env node
/**
 * Generate version.ts for each CF service.
 *
 * Uses git tag for production releases, short commit hash for dev.
 * Also captures build timestamp and environment.
 */

import { execSync } from "child_process";
import { writeFileSync, mkdirSync } from "fs";
import { resolve, dirname } from "path";
import { fileURLToPath } from "url";

const __dirname = dirname(fileURLToPath(import.meta.url));
const projectRoot = resolve(__dirname, "..");

interface VersionInfo {
  version: string;
  commit: string;
  builtAt: string;
  environment: "development" | "production";
}

function getGitInfo(): VersionInfo {
  const commit = (() => {
    try {
      return execSync("git rev-parse --short HEAD", {
        encoding: "utf-8",
        stdio: ["pipe", "pipe", "ignore"],
      }).trim();
    } catch {
      return "unknown";
    }
  })();

  let version: string;
  try {
    // Try to get the current git tag (for prod releases)
    version = execSync("git describe --tags --exact-match HEAD", {
      encoding: "utf-8",
      stdio: ["pipe", "pipe", "ignore"],
    }).trim();
  } catch {
    // No exact tag — use short commit hash
    version = commit;
  }

  const builtAt = new Date().toISOString();

  // Determine environment from CI or git tag presence.
  // Prerelease tags (e.g. -pre, -rc, -beta) deploy to dev, not production.
  const ref = process.env.GITHUB_REF ?? "";
  const isProdTag =
    ref.startsWith("refs/tags/v") && !/-(pre|rc|beta|alpha)/i.test(ref);
  const isProd = process.env.CF_ENV === "production" || isProdTag;

  return {
    version,
    commit,
    builtAt,
    environment: isProd ? "production" : "development",
  };
}

function generateVersionFile(
  servicePath: string,
  info: VersionInfo,
  serviceName: string,
) {
  const fileName = "src/lib/version.ts";
  const outputPath = resolve(projectRoot, servicePath, fileName);
  mkdirSync(dirname(outputPath), { recursive: true });

  const content = `// Auto-generated by scripts/generate-version.ts
// Do not edit manually.

export const VERSION = ${JSON.stringify(info.version)};
export const COMMIT = ${JSON.stringify(info.commit)};
export const BUILT_AT = ${JSON.stringify(info.builtAt)};
export const ENVIRONMENT = ${JSON.stringify(info.environment)};
export const SERVICE_NAME = ${JSON.stringify(serviceName)};

export interface VersionInfo {
  version: string;
  commit: string;
  builtAt: string;
  environment: string;
  service: string;
}

export function getVersionInfo(): VersionInfo {
  return {
    version: VERSION,
    commit: COMMIT,
    builtAt: BUILT_AT,
    environment: ENVIRONMENT,
    service: SERVICE_NAME,
  };
}

export function formatDuration(isoDate: string): string {
  const then = new Date(isoDate).getTime();
  const now = Date.now();
  const diff = Math.max(0, now - then);
  const seconds = Math.floor(diff / 1000);
  const minutes = Math.floor(seconds / 60);
  const hours = Math.floor(minutes / 60);
  const days = Math.floor(hours / 24);
  if (days > 0) return \`\${days}d \${hours % 24}h ago\`;
  if (hours > 0) return \`\${hours}h \${minutes % 60}m ago\`;
  if (minutes > 0) return \`\${minutes}m ago\`;
  return \`\${seconds}s ago\`;
}
`;

  writeFileSync(outputPath, content, "utf-8");
  console.log(`Generated ${outputPath}`);
  console.log(`  version: ${info.version}`);
  console.log(`  commit: ${info.commit}`);
  console.log(`  builtAt: ${info.builtAt}`);
  console.log(`  environment: ${info.environment}`);
}

const info = getGitInfo();

// Determine target from CLI args or default to all services
const target = process.argv[2];

if (!target || target === "cf-bot") {
  generateVersionFile("services/cf-bot", info, "cf-bot");
}

if (!target || target === "cf-api") {
  generateVersionFile("services/cf-api", info, "cf-api");
}

if (!target || target === "cf-worker") {
  generateVersionFile("services/cf-worker", info, "cf-worker");
}

console.log("\nVersion files generated successfully.");
