import { execSync } from "child_process";
import { writeFileSync } from "fs";
import { resolve, dirname } from "path";
import { fileURLToPath } from "url";

const __dirname = dirname(fileURLToPath(import.meta.url));
const projectRoot = resolve(__dirname, "..");

function getGitVersion(): string {
  try {
    // Try to get the latest tag, fallback to short hash
    const tag = execSync("git describe --tags --exact-match 2>/dev/null", {
      encoding: "utf-8",
      stdio: ["pipe", "pipe", "ignore"],
    }).trim();
    if (tag) return tag;
  } catch {
    // no exact tag
  }
  try {
    return execSync("git rev-parse --short HEAD", {
      encoding: "utf-8",
      stdio: ["pipe", "pipe", "ignore"],
    }).trim();
  } catch {
    return "unknown";
  }
}

function getGitCommit(): string {
  try {
    return execSync("git rev-parse HEAD", {
      encoding: "utf-8",
      stdio: ["pipe", "pipe", "ignore"],
    }).trim();
  } catch {
    return "unknown";
  }
}

function generate(serviceName: string, outPath: string) {
  const version = getGitVersion();
  const commit = getGitCommit();
  const builtAt = new Date().toISOString();
  const environment = process.env.CF_ENVIRONMENT ?? "development";

  const content = `// Auto-generated by scripts/generate-version.ts
// Do not edit manually.

export const VERSION = "${version}";
export const COMMIT = "${commit}";
export const BUILT_AT = "${builtAt}";
export const ENVIRONMENT = "${environment}";
export const SERVICE_NAME = "${serviceName}";

export interface VersionInfo {
  version: string;
  commit: string;
  builtAt: string;
  environment: string;
  service: string;
}

export function getVersionInfo(): VersionInfo {
  return {
    version: VERSION,
    commit: COMMIT,
    builtAt: BUILT_AT,
    environment: ENVIRONMENT,
    service: SERVICE_NAME,
  };
}

export function formatDuration(isoDate: string): string {
  const then = new Date(isoDate).getTime();
  const now = Date.now();
  const diff = Math.max(0, now - then);
  const seconds = Math.floor(diff / 1000);
  const minutes = Math.floor(seconds / 60);
  const hours = Math.floor(minutes / 60);
  const days = Math.floor(hours / 24);
  if (days > 0) return \`\${days}d \${hours % 24}h ago\`;
  if (hours > 0) return \`\${hours}h \${minutes % 60}m ago\`;
  if (minutes > 0) return \`\${minutes}m ago\`;
  return \`\${seconds}s ago\`;
}
`;

  writeFileSync(resolve(projectRoot, outPath), content, "utf-8");
  console.log(`Generated version info for ${serviceName}:`);
  console.log(`  version: ${version}`);
  console.log(`  commit: ${commit}`);
  console.log(`  builtAt: ${builtAt}`);
  console.log(`  environment: ${environment}`);
}

// Determine target from CLI args or default to both
const target = process.argv[2];
const allowedTargets = new Set(["cf-bot", "cf-api"]);

if (target && !allowedTargets.has(target)) {
  console.error(
    `Invalid target: ${target}. Expected one of: ${[...allowedTargets].join(", ")}`,
  );
  process.exit(1);
}

if (!target || target === "cf-bot") {
  generate("cf-bot", "services/cf-bot/src/lib/version.ts");
}

if (!target || target === "cf-api") {
  generate("cf-api", "services/cf-api/src/lib/version.ts");
}
