/**
 * Defines the types of interactions between users.
 */
export enum InteractionType {
  Like = "LIKE",
  Dislike = "DISLIKE",
  // Maybe 'BLOCK' in the future?
}

/**
 * Defines the status of an interaction.
 */
export enum InteractionStatus {
  Active = "ACTIVE", // Initial state
  Matched = "MATCHED", // When mutual like occurs
  Blocked = "BLOCKED", // If one user blocks another (future feature)
}

/**
 * Represents an interaction between two users.
 */
export interface Interaction {
  id: string; // Typically a UUID generated by the DB
  actorUserId: number; // The ID of the user performing the action
  targetUserId: number; // The ID of the user being acted upon
  type: InteractionType;
  status: InteractionStatus; // Current status of the interaction
  createdAt: Date;
}
