name: autofix.ci
on:
  pull_request:
  push:
    branches: ["main"]

permissions:
  contents: read

jobs:
  autofix:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Set up Node.js
        uses: actions/setup-node@cdca7365b2dadb8aad0a33bc7601856ffabcc48e # v4.3.0
        with:
          node-version: '24'
          cache: 'npm'
        env:
          FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

      - name: Install dependencies
        run: npm ci

      - name: Format code
        run: npx prettier --write "**/*.{ts,tsx,json,md}"

      - uses: autofix-ci/action@c5b2d67aa2274e7b5a18224e8171550871fc7e4a # v1
